meta_product_name: "SideNinjas"
meta_title: "SideNinjas - Start the side project of your dream"
meta_description: "Find the project you need to improve your skills"
meta_image: "cover.jpg" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
